// templates/typescript/src/_game.tsx
import type { Component } from 'solid-js'
import Phaser from 'phaser'
import { Game } from 'solid-phaser'

const game: Component = (props) => {
  return (
    <Game
      width={800}
      height={800}
      scale={{ mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH }}
    >
      {props.children}
    </Game>
  )
}

export default game

// examples/megabot/src/_game.tsx
import { Game } from 'solid-phaser'

export default (props) => {
  return (
    <Game
      width={400}
      height={225}
      physics={{
        default: 'arcade',
        arcade: {
          // debug: true,
          gravity: {
            y: 1000,
          },
        },
      }}
      dom={{
        createContainer: true,
      }}
      parent={document.querySelector('#root') as HTMLElement}
      render={{ pixelArt: true }}
      scale={{ mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH }}
    >
      {props.children}
    </Game>
  )
}
